### PR TITLE
Microverse JS Capstone: Feature/header section

### PR DESCRIPTION
**Pull request by Megagig**
### **In this milestone,I:**
-Created page header according to the wireframe

- Style the header section

### CODE REVIEW

**Comment by Benawi** [comment]
Hi @Megagig ,

You did extremely great on this project! 👏 👏
There are however a few issues that you still need to work on linters bug but you are almost there!
🏁 🚦 ⛪ 🚜 🏃 🌴 🏫 🌳 🏘️

**Review by Benawi — CHANGES_REQUESTED** [review]
## Required Changes ♻️
Hi @Megagig ,

You did extremely great on this project! 👏 👏
There are however a few issues that you still need to work on linters bug but you are almost there!
 🚦

**Comment by Megagig** [comment]
Thanks so much @Benawi , i have fixed the linters errors

**Review by Benawi — APPROVED** [review]
Hi @Megagig 
Your sub task of project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

**Pull request merged**
